log:
  directory: ./logs
projects:
  dbpedia-en:
    shaclFile: ./config/dbpedia-en/config.ttl
    sparqlEndpoint: https://dbpedia.org/sparql
    domains:
      - sparna-git.github.io
    cache:
      urilookup: ./cache/dbpedia-en/urilookup_cache.json
    reconciliation:
      implementation: SparqlReconcileService
      cacheSize: 1000
      maxResults: 2
    text2query:
      implementation: MistralText2QueryService
      agentId: ag:33fd9714:20250822:t2q-post-process:a046f692
    query2text:
      implementation: MistralQuery2TextService
      agentId: ag:33fd9714:20250507:untitled-agent:d1fc8155
  demo-ep:
    shaclFile: ./config/demo-ep/config.ttl
    sparqlEndpoint: http://graphdb.sparna.fr/repositories/endorse2025
    domains:
      - sparna-git.github.io
    cache:
      urilookup: ./cache/demo-ep/urilookup_cache.json
    reconciliation:
      implementation: SparqlReconcileService
      cacheSize: 1000
      maxResults: 2
    text2query:
      implementation: RestText2QueryService
      agentId: ag:33fd9714:20251002:t2q-org-ep:e1a9d878
    query2text:
      implementation: RestQuery2TextService
      agentId: ag:33fd9714:20250507:untitled-agent:d1fc8155
