log:
  directory: ./logs
projects:
  dbpedia-en:
    shaclFile: ./config/dbpedia-en/config.ttl
    sparqlEndpoint: https://dbpedia.org/sparql
    endpoints-agents:
      MISTRAL_AGENT_ID_query_2_text: <MISTRAL_AGENT_KEY>
      MISTRAL_AGENT_ID_text_2_query: <MISTRAL_AGENT_KEY>
    domains:
      - sparna-git.github.io
    cache:
      urilookup: ./cache/dbpedia-en/urilookup_cache.json
  demo-ep:
    shaclFile: ./config/demo-ep/config.ttl
    sparqlEndpoint: http://graphdb.sparna.fr/repositories/endorse2025
    endpoints-agents:
      MISTRAL_AGENT_ID_query_2_text: <MISTRAL_AGENT_KEY>
      MISTRAL_AGENT_ID_text_2_query: <MISTRAL_AGENT_KEY>
    domains:
      - sparna-git.github.io
    cache:
      urilookup: ./cache/demo-ep/urilookup_cache.json
